### ISSUE TITLE
Altium files. Save as ASCII

### ISSUE THREAD

**Issue by colin-ab** [lnls-dig/rtm-lamp-hw#15]
Can the be saved as ASCII files so they can be imported into other eCAD software packages?

**Comment by augustofg** [comment]
Hi @colin-ab . I've converted the PCB and schematic files to ascii and put them on a new branch. Please check the [altium-ascii-conv](https://github.com/lnls-dig/rtm-lamp-hw/tree/altium-ascii-conv) branch.

**Comment by colin-ab** [comment]
Many thanks. That's great. Colin-ab @ Diamond Light Source
