### ISSUE TITLE
Driving the DAC output from high to low causes interference in the current measurement

### ISSUE THREAD

**Issue by augustofg** [lnls-dig/rtm-lamp-hw#9]
Channels 0, 2, 3, 5, 6, 8 and 9 are picking up interference from the DAC in the current measurement circuitry. Only when the DAC output swings from 4V to 0V the interference occurs suggesting it might be a grounding issue.

![ch00_dac_interf](https://user-images.githubusercontent.com/8903198/122448997-c0f2d980-cf7b-11eb-9755-db96dbc72637.png)

**Comment by danielot** [comment]
Note: these measurements were taken when opamps were disabled/powered off.

**Comment by augustofg** [comment]
Removing R83 and soldering a 33 ohms resistor directly to the positive and negative inputs of the AD8429 (IC29) makes the glitch to disappear from the input, but the output still behaving the same. One thing I observed it that the positive and negative power supplies, when measuring directly from the inamp pins, show a large voltage glitch (1 - 2Vpp) that might explain this issue:

![inamp_supply_interf](https://user-images.githubusercontent.com/8903198/122786456-b6418880-d28a-11eb-8390-2dda5968f96b.png)

Unfortunately, I couldn't reproduce this in spice, but maybe the [model](https://www.analog.com/media/en/simulation-models/spice-models/ad8429.cir) is not accurate enough.

[rtm-lamp-ad8429-simu.zip](https://github.com/lnls-dig/rtm-lamp-hw/files/6688372/rtm-lamp-ad8429-simu.zip)

**Comment by danielot** [comment]
Do these glitches on the +/-7V power supply happen for positive DAC steps too? It would be nice to see the curves for the positive step as well.

**Comment by augustofg** [comment]
@danielot They do, but at a lower amplitude.

**Comment by augustofg** [comment]
~OK now it seems I'm getting somewhere. Maybe my first attempt to solder an 33 ohms resistor directly into the AD8429 differential inputs wan't making good contact. I've re-soldered it and the glitch is almost gone in channel 8:~

![ch8_dac_interf_shunt_removed](https://user-images.githubusercontent.com/8903198/124326148-5be2da80-db5c-11eb-843c-e1cfc4e04415.png)

I'll try this for the other channels just to be sure.

**Comment by augustofg** [comment]
My mistake, the AD8429 from channel 8 was not powered (I removed the ferrite beads from the AD8429 to test if the disturbances in the +-7V supplies were conducted or irradiated). Here there are the same measurements for channel 5 with the shunt resistor removed and a 30 ohms resistor soldered directly to the inamp differential inpunts:
![ch5_dac_interf_shunt_removed](https://user-images.githubusercontent.com/8903198/124474753-4990b880-dd77-11eb-9280-2679702b23ec.png)

**Comment by augustofg** [comment]
It is a grounding issue. After soldering wires to reduce the ground impedance for C85, C84, C88 and C89 I was able to reduce the glitch amplitude significantly:
![ch5_gnd_fix2](https://user-images.githubusercontent.com/8903198/124983132-fbe1ad80-e00d-11eb-9266-c17521eb0d3a.png)

Fix 1:
![ch5_gnd_top_fix1](https://user-images.githubusercontent.com/8903198/124983597-8cb88900-e00e-11eb-957f-93e193ad3ad1.jpg)

Fix 2:
![ch5_gnd_top_fix2](https://user-images.githubusercontent.com/8903198/124983603-8de9b600-e00e-11eb-94ad-520c9c3af846.jpg)

**Comment by augustofg** [comment]
Solved in the newer releases.
